on: [push]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dotnet
        run: choco install dotnetcore

      - name: initialize nuget creds
        run: dotnet nuget add source https://pkgs.dev.azure.com/mseng/_packaging/ComponentGovernance/nuget/v3/index.json --password ${env:NUGET_AUTH_TOKEN} --username notused --store-password-in-clear-text --name CGReader
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_FEED_PAT }}

      - name: Restore packages
        run: dotnet restore

      - name: Run Tests
        run: dotnet test cgmv.sln -restore:False
